name: Keepalive Workflow
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC午夜运行
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2  # 自动创建虚拟提交
